# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(help_text='Is this user account activated?', max_length=20)),
                ('department', models.CharField(max_length=10, null=True)),
                ('position', models.CharField(max_length=10, null=True)),
                ('contact', models.CharField(max_length=11, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='static/signature/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this user account activated?')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_classification', models.CharField(choices=[('연차', '연차'), ('오전반차', '오전반차'), ('오후반차', '오후반차'), ('병가', '병가'), ('경조사휴가', '경조사휴가'), ('산전후휴가', '산전후휴가'), ('기타', '기타')], default='연차', max_length=5)),
                ('emergency_contact', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=30)),
                ('comments', models.PositiveSmallIntegerField(default=0, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Approval')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
